export const resume = {
    techStack: [
        'Git',
        'GitHub',
        'MySQL',
        'PostgreSQL',
        'MongoDB',
        'GitLab',
        'HTML/CSS/SCSS',
        'Bootstrap/TailwindCSS',
        'Javascript',
        'Typescript',
        'Node.js',
        'express.js',
        'koa.js',
        'Nest.js',
        'Prisma/TypeORM/Sequelize',
        'Mongoose',
        'telegraf.js',
        'node-telegram-bot-api',
        'Docker',
        'Linux',
        'Deploying',
        'GraphQL',
        'Adobe Photoshop',
        'Figma',
        'Postman/Insomnia',
        'Vue.JS',
        'Vue Router',
        'VueX',
    ],
    name: "Abdusalomov A'zamjon",
    job: 'Junior Full Stack developer',
    phoneNumber: '+998-88-670-26-62',
    email: 'abdusalomovdev@gmail.com',
    location: 'Tashkent, Uzbekistan',
    github: {
        link: 'https://github.com/abdusalomovdev',
        title: 'github.com/abdusalomovdev',
    },
    summaryText: [
        '-Experience with Backend Development using Node.js, Express.js and Nest.js and koa.js',
        '-Experience with SQL & NoSQL databases using MongoDB and PostgreSQL & MySQL',
        '-Experience with Telegram bots using telegraf.js and node-telegram- bot-api',
        '-Experience with Web Apps with Vue.js, TailwindCSS, Vue Router, VueX',
    ],
    experience: [
        {
            companyName: 'Homedev.uz',
            fromTo: '01/2023 - 04/2023',
            workedAs: 'Backend Developmer internship',
            location: 'Tashkent, Uzbekistan',
            description:
                'Homedev is a global services company that provides customers with access to products, insights and experiences that enrich lives and build business success.',
        },
        {
            companyName: 'Codetech',
            fromTo: '04/2023 - 07/2023',
            location: 'Tashkent, Uzbekistan',
            workedAs: 'Junior Backend Developer',
            description:
                'Codetech is outsort company that develops web, mobile, desktop applications, telegram bots an etc.',
        },
    ],
    education: [
        {
            title: 'Foundation Programming',
            where: "Najot Ta'lim",
            fromTo: '02/2022 - 07/2022',
            location: 'Tashkent, Uzbekistan',
            description:
                'Learned algorithms and foundations of programming with languages C and Python with MySQL database',
        },
        {
            title: 'Full Stack Bootcamp (Node.js + Vue.js)',
            where: "Najot Ta'lim",
            fromTo: '08/2022 - 04/2023',
            location: 'Tashkent, Uzbekistan',
            description:
                'Learned Frontend and Backend development with HTML/CSS/JS, TailwindCSS, Bootstrap, Typescript, Node.js, and Vue.js (VueX + Pinia)',
        },
    ],
};
